(source gnu)
(source melpa)
(source org)

(depends-on "cask")
(depends-on "f")
(depends-on "s")
(depends-on "projectile")
(depends-on "org-ref")
(depends-on "geiser")
(depends-on "string-inflection")
(depends-on "org-ref+"
            :git "https://github.com/brandonwillard/org-btw.git"
            :branch "master")
(depends-on "ox-latex+"
            :git "https://github.com/brandonwillard/org-btw.git"
            :branch "master")
